name: secrets

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out repository
        uses: actions/checkout@v2
        
      - name: Initiating Sensitive Information Scan using Truffle Hog
        run: |
          pip install truffleHog3
          trufflehog3 --no-history --format json --output trufflehog.json
          trufflehog3 -R trufflehog.json --output trufflehog.html
          curl --upload-file ./trufflehog.html https://transfer.sh/trufflehog.html
          
